# Generated by Django 4.2 on 2023-05-18 07:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0003_recipe_favorite_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='favorite_count',
        ),
        migrations.RemoveField(
            model_name='shoppinglist',
            name='created_at',
        ),
        migrations.AddField(
            model_name='shoppinglist',
            name='recipes',
            field=models.ManyToManyField(to='recepies.recipe', verbose_name='Рецепты'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Время приготовления'),
        ),
        migrations.DeleteModel(
            name='ShoppingListItem',
        ),
    ]
