# Generated by Django 4.2 on 2023-05-24 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recepies', '0006_remove_shoppinglist_recipes_shoppinglist_recipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recepies.RecipeIngredient', to='recepies.ingredient', verbose_name='Ингридиенты'),
        ),
    ]
